### ISSUE TITLE
Clean Url

### ISSUE THREAD

**Issue by cybermano** [mrjcgoodwin/MarkupGoogleTranslate#2]
It seems that cleanUrl() method sometimes will brake google translate url, expecially when already present the hyphens (much more in second level pages).

I changed
```
    private function cleanUrl($url) {
        $cleanUrl = str_replace('-','--',$url);
        $cleanUrl = str_replace('.','-',$cleanUrl);
        return $cleanUrl;
    }
```
with ( commented first str_replace() )
```
    private function cleanUrl($url) {
        // $cleanUrl = str_replace('-','--',$url);
        $cleanUrl = str_replace('.','-',$url);
        return $cleanUrl;
    }
```
and for me it works fine.
#### Before
![Url_1](https://user-images.githubusercontent.com/66470231/235749624-fa09b4de-5bd2-4c6f-81f5-5fd6c35a50a6.png)
#### After
![Url_2](https://user-images.githubusercontent.com/66470231/235749640-0e05325b-73cb-427d-9633-09cb3dfc1016.png)

**Comment by mrjcgoodwin** [comment]
@cybermano Do I assume you resolved this yourself in your recent PR?

**Comment by cybermano** [comment]
Yes, I definitely removed the first "replaced" and no errors occurred.
